### ISSUE TITLE
Empty module

### ISSUE THREAD

**Issue by monicapatel21** [wri/wri_sites#105]
add something like wri-indonesia (or whichever country) for site-specific configurations

some things will always need changes made in profile in site folder (that you can't do in custom module), but there are plenty that you can do

downside: extra location to look for when troubleshooting, but we'll get into the habit of this -- and plan to do for all sites that could use it (including retroactively china).

questions:  
- is there a theme component?  (where a logo height is specific to a site)
- child themes: only to facilitate development side of things // makes sense in context of indonesia (but we can play this by ear). if something shows up that requires going back to re-work, then it makes sense to open this can of worms

**Comment by mariacha** [comment]
We don't have a thing that needs this right now, so I'm closing.
