### ISSUE TITLE
GDPR research

### ISSUE THREAD

**Issue by monicapatel21** [wri/wri_sites#107]
Would like suggestions and advice on a feature that’ll work across multiple sites – as well as across Drupal and WordPress
Look into 3rd party service to accomplish (a)
Budget for effort once tool decision is made
Ask rest of ThinkShout about 3rd party solution success

**Comment by mariacha** [comment]
It sounds like our team hasn't implemented something like this across multiple sites yet. The closest we have come is:

I researched this service which gives good detail on how to implement the tracker: https://cookie-script.com/how-to-block-third-party-cookies.html

**Comment by StudioZut** [comment]
Thanks!
