### ISSUE TITLE
Twitter meta description

### ISSUE THREAD

**Issue by monicapatel21** [wri/wri_sites#121]
Question about meta **description** pulling into twitter from https://www.wri.org/research/state-climate-action-2022

The description in there when first posted comes in from chat...

**Comment by shannon-paton** [comment]
Tweet in question: https://twitter.com/WorldResources/status/1587428032821841928

![Screen Shot 2022-11-01 at 1.10.40 PM.png](https://images.zenhubusercontent.com/61c0eb73bbc0d05d795dd9f9/bc6c2ff6-2585-42e2-b364-3bcf5d3ad103)

Final meta description, set in CMS should be "The State of Climate Action 2022 measures the global gap in climate action, highlighting where progress must accelerate to keep the 1.5°C temperature limit within reach."

**Comment by shannon-paton** [comment]
Tweet in question: https://twitter.com/WorldResources/status/1587428032821841928

![Screen Shot 2022-11-01 at 1.10.40 PM.png](https://images.zenhubusercontent.com/61c0eb73bbc0d05d795dd9f9/bc6c2ff6-2585-42e2-b364-3bcf5d3ad103)

Final meta description, set in CMS should be "The State of Climate Action 2022 measures the global gap in climate action, highlighting where progress must accelerate to keep the 1.5°C temperature limit within reach."

**Comment by monicapatel21** [comment]
@StudioZut i still can't seem to assign this to @katieescoto in case you can help with that?

**Comment by mariacha** [comment]
Sounds like the twitter card cache isn't something we have a lot of control over. This url gives some options for refreshing things:
https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/troubleshooting-cards#refreshing

but YMMV for it. Using bit.ly seems like the most stable recommendation.
