### ISSUE TITLE
Slow site performance on wri.org

### ISSUE THREAD

**Issue by katieescoto** [wri/wri_sites#122]
**Describe the bug**
From Christian:
"Backend performance is pretty bad, tagging including languages, tags/topics, adding additional fields, etc. There's an issue on the Pantheon status page https://status.pantheon.io/ but don't think it's related.  There's also an issue in watchdog from 13 hours ago but hasn't recurred https://dashboard.pantheon.io/sites/29dfa634-88ba-4ba3-a88c-377f3b9656d2#live/errors/error-log"

**Comment by mariacha** [comment]
+1 to what Katie said -- we're not sure how the filesystem slowdown could have been related to the backend slowdown, but the coincidence of it sort of matching up with the times Pantheon was having trouble, plus my vague idea that maybe it could be related to twig templates (which use the filesystem) makes this feel like something we can keep an eye on but probably don't need to sink a lot of time into investigating unless it happens again.

**Comment by mariacha** [comment]
This seems resolved.
