### ISSUE TITLE
Support: Initial Updates & Onboarding

### ISSUE THREAD

**Issue by monicapatel21** [wri/wri_sites#124]
Add to routine support updates (or provide status updates for):

- [x] [forestlegality.org](https://forestlegality.org/) - Deployed
Latest: Bob set up locally, has updates in progress, seeing errors on multidev and will work to resolve
Pantheon site name = 'forestlegality'

up for review here: https://kupdates-forestlegality.pantheonsite.io/

Updates applied through interface, but needed to troubleshoot some errors through the console.

- [x] [wrisehirler.org](https://wrisehirler.org/) - Updates applied successfully through console. Ready for testing: https://updates-wrisehirler1.pantheonsite.io/
May need D9 update (another vendor is involved)
Pantheon site name = '[wrisehirler.org](http://wrisehirler.org/)' "Ross Cities Turkey"

- [x] research.wri.org  - To the client for testing
- [ ] Notes:
- redirects to WRI.org
-- https://research.wri.org/gfr/global-forest-review
-- https://research.wri.org/wrr-food 
Priority 2: Paused until D9 update - Feature dev in progress (they've worked with another vendor on updates so we'll need to pause on updates)
- Just whatever is available for D8 if anything:
- Core updated to the last possible D8 version, 8.9.20
- Updated to PHP 7.4 (I was getting errors trying to upgrade core)
- Replaced drupal-composer/drupal-scaffold with core-composer-scaffold
- Tried to switch a patch that was not applying, but the new one doesn't apply either. There is an error, but again, not sure if it's worth troubleshooting. Removed the patch, as it is slowing down updates.
- Trying to focus on updating any module versions that are no longer supported (to the extent they can be updated)
- Updated to Footnotes 3.0.0
- Updated Sitemap to 2.0.0-beta3
- Updated to Super Login 2.0.0
- Updated to Switch Page Theme 3.3.0-alpha1
- Updated to Taxonomy Manager 2.0.7
- Updated to Webform 6.1.3
- Tried to update Extlink, but it would need more troubleshooting than is probably necessary, so I reverted that back
- Ran database updates
- Up on a multidev: https://q4-updates-wri-publications.pantheonsite.io/gfr/global-forest-review

- [x] [thecityfix.com](https://thecityfix.com/) - Updates applied successfully through interface. Available for testing here: https://updates-thecityfix-sandbox.pantheonsite.io/
Priority 1: Team occasionally works with outside team to get work done -- Christian will confirm that is paused and we can then resume this
Pantheon site name = 'thecityfix-sandbox'

- [x] [thecityfixturkiye.com](https://thecityfixturkiye.com/) - Updates applied successfully through the interface. Available for testing here: https://updates-thecityfixturkiye.pantheonsite.io/
Priority 3: converted to standalone from a very long WP Multisite, which is likely to cause some complications
Pantheon site name = 'thecityfixturkiye'

- [x] [buildingefficiencyaccelerator.org] - Updates applied successfully through the interface. Available for testing here: https://updates-buildingefficiencyaccelerator.pantheonsite.io/
(https://buildingefficiencyaccelerator.org/)
Priority 4: old, but pretty simple blog site -- no major issues expected
Pantheon site name = 'buildingefficiencyaccelerator'

([Rows 2, 4, 5, 8, 9 and 10](https://docs.google.com/spreadsheets/d/1bp2jAzgozwQTECs63LzSvVJqTU4EOC4qnECNC1TCLAI/edit#gid=1617391067))

**Comment by katieescoto** [comment]
@wthomaswri The rest of the sites are also ready for review. Each one has a link to the updates test environment. Can you take a look when you have a chance? In the meantime, I am troubleshooting the wrr-food issues from yesterday.

**Comment by monicapatel21** [comment]
Consolidated all review links here:

[forestlegality.org](https://forestlegality.org/) 
- [ ]  https://kupdates-forestlegality.pantheonsite.io/

 [wrisehirler.org](https://wrisehirler.org/) -  
- [ ] https://updates-wrisehirler1.pantheonsite.io/

 research.wri.org:

-- https://research.wri.org/gfr/global-forest-review
- [ ] https://q4-updates-wri-publications.pantheonsite.io/gfr/global-forest-review

-- https://research.wri.org/wrr-food - IN PROGRESS

 [thecityfix.com](https://thecityfix.com/)
- [ ] https://updates-thecityfix-sandbox.pantheonsite.io/

 [thecityfixturkiye.com](https://thecityfixturkiye.com/)
- [ ] https://updates-thecityfixturkiye.pantheonsite.io/

 [buildingefficiencyaccelerator.org](https://buildingefficiencyaccelerator.org/)

- [ ] https://updates-buildingefficiencyaccelerator.pantheonsite.io/

**Comment by wthomaswri** [comment]
Hi @katieescoto,

1. wrisehirler.org, thecityfix.com, buildingefficiencyaccelerator: Good

2. thecityfixturiye:

- there's a php warning appearing on some pages like this: https://updates-thecityfixturkiye.pantheonsite.io/siz-de-yazin/

- there's some strange spacing on blogs between first paragraphs and the image that follows: https://updates-thecityfixturkiye.pantheonsite.io/ipccnin-2021-iklim-raporundan-5-onemli-bulgu/

should be like this: https://thecityfixturkiye.com/ipccnin-2021-iklim-raporundan-5-onemli-bulgu/

**Comment by katieescoto** [comment]
@wthomaswri I think we've got the publications sites working. Can you take one more look here: https://dev-wri-publications.pantheonsite.io/wrr-food/table-contents-synthesis. These are the sites that had the conjoined nav and background repeat header images.

**Comment by wthomaswri** [comment]
Think it looks good @katieescoto

**Comment by katieescoto** [comment]
@wthomaswri WRI Publications is deployed and City Fix Turkey is ready for final review.

**Comment by katieescoto** [comment]
@monicapatel21 all these are complete, so I'm closing this ticket
