### ISSUE TITLE
Spaces in top-level terms for resource types entity reference broken

### ISSUE THREAD

**Issue by mariacha** [wri/wri_sites#142]
**Describe the bug**
For this view: 
/admin/structure/views/view/resource_types

if you pass in "Technical Perspectives" the view searches for "Techincal" and "Perspective" and you don't get the results you want.

**Additional context**
There's a patch for this at https://www.drupal.org/project/drupal/issues/672606 that we used to apply, but at some point we lost that patch. My thinking is I pulled the wrong one on accident when this issue was closed:
https://www.drupal.org/project/drupal/issues/2693787

I'll do some git bisecting to make sure this is true, then update the patches.

### How to test
- [ ] Make sure the node/add page continues to work for all content types.

**Comment by mariacha** [comment]
Hmm. The patch does not solve this. They explicitly test that a space is broken if you're using the + method, which is really obnoxious.

The whole reason we're doing this this way is to make the view not depend on the id of the taxonomy term, which may change from site to site. 

Anyway, I'm going to try a custom handler.

**Comment by mariacha** [comment]
This is up and ready for review on develop:
https://develop-wriflagship.pantheonsite.io/node/add/article

Technical Perspective is in the list.

**Comment by wthomaswri** [comment]
Looks good @mariacha
