### ISSUE TITLE
Site setup: India

### ISSUE THREAD

**Issue by mariacha** [wri/wri_sites#151]
**Describe the bug**
Sets up a new site `wri-india`

## Dev tasks:
- [x] Follow the steps in the readme for the starter kit at  https://github.com/wri/wri-starter-kit#wri-starter-kit including the "Post install configuration"
- [x] Although that readme has "What to do if things fail" https://github.com/wri/wri-starter-kit#what-to-do-if-the-buildproject-command-fails section, those steps are not  correct. Please update that section with the real thing to do if a project fails (drafted out roughly here):
  - Start by trying to delete the site: https://github.com/wri/wri-starter-kit#how-to-delete-a-project-made-with-this-starter-kit
  - If that fails, delete the github repo and the pantheon environment manually.
  - Fix the problems that caused the site to fail to build
  - Re-run the `terminus build:project:create`
- [x] Get started setting up the migration for wri-india  using the instructions here: https://github.com/wri/wri_migration#migration-documentation-for-the-wri_sites-repo-for-migrating-from-d7-to-d89
- [x] Once this is complete, copy this ticket to make a `wri-espanol` site.

## This ticket is  done when:
- [x] There is a wri-india repository on github
- [x] There is a wri-india.live site on Pantheon
- [x] There is a module "wri_migration" enabled on the wri-india site.

**Comment by monicapatel21** [comment]
- Mexico team = content migration planning with Shannon (we'll have some decisions on migration)
- Mid-May will also give us final confirmation about what español will be called (Latin America, e.g.)
-- country pages would be more emphasized / tagging re-think for content teams, but same site structure (how Africa site will be set up)
- ThinkShout next step: Do a first run of migration with Mexico content

**Comment by monicapatel21** [comment]
[wri-india-content-audit.xlsx](https://github.com/wri/wri_sites/files/11325854/wri-india-content-audit.xlsx)
[Mexico Content Audit.xlsx](https://github.com/wri/wri_sites/files/11325855/Mexico.Content.Audit.xlsx)
