### ISSUE TITLE
Site setup: Español

### ISSUE THREAD

**Issue by katieescoto** [wri/wri_sites#154]
**Describe the bug**
Sets up a new site `wri-espanol`

## Dev tasks:
- [x] Follow the steps in the readme for the starter kit at  https://github.com/wri/wri-starter-kit#wri-starter-kit including the "Post install configuration"
- [x] Although that readme has "What to do if things fail" https://github.com/wri/wri-starter-kit#what-to-do-if-the-buildproject-command-fails section, those steps are not  correct. Please update that section with the real thing to do if a project fails (drafted out roughly here):
  - Start by trying to delete the site: https://github.com/wri/wri-starter-kit#how-to-delete-a-project-made-with-this-starter-kit
  - If that fails, delete the github repo and the pantheon environment manually.
  - Fix the problems that caused the site to fail to build
  - Re-run the `terminus build:project:create`
- [x] Get started setting up the migration for wri-espanol  using the instructions here: https://github.com/wri/wri_migration#migration-documentation-for-the-wri_sites-repo-for-migrating-from-d7-to-d89

## This ticket is  done when:
- [x] There is a wri-espanol repository on github
- [x] There is a wri-espanol.live site on Pantheon
- [x] There is a module "wri_migration" enabled on the wri-espanol site.

**Comment by mariacha** [comment]
Adding the content audit: [Mexico Content Audit.xlsx](https://github.com/wri/wri_sites/files/11325855/Mexico.Content.Audit.xlsx)

**Comment by katieescoto** [comment]
Thank you! Content translation settings have been set and I'm working on the configuration translation ones.

**Comment by katieescoto** [comment]
Handing over to you @mariacha. What's left is:

- Content translation settings are done and all config langcode settings have been switched to "es" from "en", but still need to align config translation settings to mirror those in WRI Indonesia
- Migration module is committed, but the build is failing still so it hasn't yet been enabled on live

**Comment by mariacha** [comment]
Great! Taking over

**Comment by mariacha** [comment]
Closing  this one for https://github.com/wri/wri-espanol/issues/2
