### ISSUE TITLE
Uninstall Onlyone on profile

### ISSUE THREAD

**Issue by mariacha** [wri/wri_sites#158]
It looks like China and Flagship are the only ones using this, which basically is just a guardrail to keep people from creating a bunch of homepages and thinking they'll be the official homepage. At this point, maybe that's too much of a guardrail, and the site owners don't really need it? Let's discuss!

## Dev tasks
- [x] Remove `onlyone` as a requirement for the `wri_homepage` module: https://github.com/wri/wri_sites/blob/1a3bd27e55ed8287f2335ef2e48ab9ffc551a4c9/modules/wri_homepage/wri_homepage.info.yml#L10
- [x] Ensure the module is uninstalled on all IOs on live (blocked by 9.5.1 release on flagship)
- [x] Remove references to onlyone from all IO `composer.json` files.

**Comment by monicapatel21** [comment]
OK to remove module -- we can bring it back indivually if we need it

**Comment by gustavorf** [comment]
Ready to test.

**Comment by mariacha** [comment]
This is uninstalled on all sites, so I'm closing.
