### ISSUE TITLE
ForestLegality security updates check

### ISSUE THREAD

**Issue by monicapatel21** [wri/wri_sites#160]
In ticket #124 we deployed updates to forestlegality and other WRI microsites, but I don't see them on this list: 

https://docs.google.com/spreadsheets/d/1QrQ-Z8B5XqWjO1ct0voCc3PfG4PENSouu9nQzc8-AzU/edit#gid=0
or this one:
https://docs.google.com/spreadsheets/d/16bUo0GzPK9LH2q-YbGRiwx5BIK3bGNaqhVhP5yZZ6ZM/edit#gid=0

So I can use your help answering this client question: 
for maintenance, is there anything in the pipeline for forestlegality.org? If not we may do some updates in-house from Christian

cc: @robertjpotter

**Comment by robertjpotter** [comment]
hi @monicapatel21 looks like that site didn't get added to either sheet spreadsheets. I've added to our support tracking sheet and Katie is adding to the All Sites Technical sheet. 

We have not started those updates for this quarter yet. We can get them added to this next sprint, starting next week, or Christian can handle internally if he would prefer.

**Comment by monicapatel21** [comment]
Thank you @robertjpotter ! Go ahead and add and I'll confirm with Christian. Thanks for letting me know.

**Comment by robertjpotter** [comment]
hi @monicapatel21 Yup, that's the plan. We haven't done this quarter's updates for WRI yet though. We can start on those in the sprint that starts next week. Is there any specific order or priority they'd like for updates?

**Comment by monicapatel21** [comment]
Nope -- do what you do best (what makes sense). TY for checking!

**Comment by monicapatel21** [comment]
Hi @robertjpotter and @katieescoto a heads up for y'all that client needs this forestlegality.org updated sooner rather than later. They'll be taking on updates in-house for this round to make that happen so this is off your list. Thanks!
