### ISSUE TITLE
Design help needed - Spring 2023

### ISSUE THREAD

**Issue by monicapatel21** [wri/wri_sites#163]
Here's a background Zoom: 

https://thinkshout.zoom.us/rec/share/p6SQRLyY8aOXDPkG69ZI_3ksTs-Iao31KNrnjK9L6NXJxYgc9JN0otHbyie7l2t0.EmND8S0EEEPRV0kt
Passcode: C&spMCy5

**Comment by mariacha** [comment]
I'm going to close this.
