### ISSUE TITLE
Enable Subpages for Robust Publications

### ISSUE THREAD

**Issue by wthomaswri** [wri/wri_sites#164]
Hi @mariacha 

We're looking to create a robust publication for WRI Brasil but it looks like subpages are not fully associated with the main pub page and subnav like for Projects and Microsites. I enabled 'publications' on the Subpage parent page config option to be able to make the associations but there are some extra steps it seems.

Here is an example: https://publication-wri-brasil.pantheonsite.io/publicacoes/amazon-story/section-1

**Comment by wthomaswri** [comment]
This is great. Thanks @mariacha. Yeah it looks like it's not set on flagship to work. I looked at the display modes and see that there isn't one for Hero on Subpage

**Comment by mariacha** [comment]
Ok cool, so we'll need a little development to get the right fields turned  on for that content type, and we'll export the settings from that multidev to get a jump start on that display mode. Shouldn't be too hard!

**Comment by shannon-paton** [comment]
Hi @mariacha  just flagging something I noticed while working on staging the page for Brasil. We need to set the subnav so that it stays behind the download modal.

![Screen Shot 2023-05-15 at 1.44.29 PM.png](https://images.zenhubusercontent.com/61c0eb73bbc0d05d795dd9f9/880f96a6-a61e-405d-a9a8-e5d47b3ebbec)

**Comment by mariacha** [comment]
I put this fix up on the publications multidev directly: https://publication-wri-brasil.pantheonsite.io/publicacoes/amazon-story/section-1#

and fixed the download modal/navigation issue:
https://publication-wri-brasil.pantheonsite.io/publicacoes/amazon-story#O_que_%C3%A9_a_NEA?

If that looks good, we can plan on deploying that to Brasil on Thursday during the usual timeslot.

**Comment by wthomaswri** [comment]
This looks great, thanks so much @mariacha. One other small request - is there an easy way to have the hero download button show on all subpages? I guess if there were cases where we didn't want to show it, we could hide through asset injector.

**Comment by mariacha** [comment]
I'm pushing up the button fix now. I also am seeing some trouble with that z-index fix for the modal showing up under the navigation button -- it's causing the main nav to go behind elements on the hero, so I'll fix that, but it will likely not be back to you until the morning.

**Comment by mariacha** [comment]
Ok, this is fixed now! @wthomaswri https://publication-wri-brasil.pantheonsite.io/publicacoes/amazon-story/section-1

**Comment by wthomaswri** [comment]
Looks great @mariacha

**Comment by mariacha** [comment]
This work is up on Brasil's live site already, but leaving it  in the "Deploy to Flagship" column because it will go to Flagship next.

**Comment by mariacha** [comment]
QA-able on:
- [ ] Brasil: https://develop-wri-brasil.pantheonsite.io/publicacoes/guia-para-areas-de-transito-calmo/test-supbage
- [ ] China:
- [ ] Indonesia:

**Comment by shannon-paton** [comment]
looks good

**Comment by shannon-paton** [comment]
And on China https://develop-wri-china.pantheonsite.io/en/en/research/testimony-subcommittee-energy-and-power-transformation-chinas-energy-system/test

**Comment by mariacha** [comment]
This work is deployed to the IOs. There are two followup tickets for handling the language bugs https://github.com/wri/wri_sites/issues/197 and https://github.com/wri/wri_sites/issues/196
