### ISSUE TITLE
Uninstall GDPR module

### ISSUE THREAD

**Issue by mariacha** [wri/wri_sites#170]
Osana is doing this now, take the gdpr_compliance module out of this repo.

## Dev tasks
- [x] Remove the `gdpr_compliance` module from the `composer.json` in `wri_sites`https://github.com/wri/wri_sites/blob/main/composer.json

**Comment by gustavorf** [comment]
Ready to test.

**Comment by mariacha** [comment]
Confirmed on:
- [ ] Brasil
- [ ] China
- [ ] Indonesia

**Comment by mariacha** [comment]
This is done on all sites
