### ISSUE TITLE
Q2 Updates

### ISSUE THREAD

**Issue by katieescoto** [wri/wri_sites#176]
- [x] [forestlegality.org](http://forestlegality.org/) - **Deployed**
Ready for review: https://q2-updates-forestlegality.pantheonsite.io/

- [ ] https://research.wri.org/gfr/global-forest-review
- [ ] https://research.wri.org/wrr-food
- [x] [thecityfix.com](https://thecityfix.com/) - **Deployed**
CityFix up for review: https://q2-updates-thecityfix-sandbox.pantheonsite.io/. All plugins that have been tested on this version of WP have been updated to the following:

- WP 6.2.2
- Disqus Comment System 3.0.23
- Google Analytics for WordPress by MonsterInsights 8.15
- Google XML Sitemaps 4.1.11
- Redirection 5.3.10
- Simple Local Avatars 2.7.5
- WordPress Importer 0.8.1
- WP Optimize 3.2.15
- WP PageNavi 2.94.1
- WP Touch 4.3.53

- [x] https://thecityfixturkiye.com/ - **Deployed**
TheCityFix Turkiye [up for review](https://q2-updates-thecityfixturkiye.pantheonsite.io/). Not too many plugin updates here. The ones it’s calling for are WP Migrate DB Pro, WP Migrate DB Pro Media Files, and WP Migrate DB Pro Multisite Tools, but it’s asking for a license key. Let me know if this is available somewhere, and I can upgrade those as well. Core has been upgraded to 6.2.2.

- [x] https://buildingefficiencyaccelerator.org/ - **Deployed**
[Building Efficiency Accelerator](https://q2-updates-buildingefficiencyaccelerator.pantheonsite.io/) is ready for review. The following updates are included:
Core upgrated to 6.2.2
ACF Better Search to 4.1.0
Contact Form 7 to 5.7.7
Duplicate Page to 4.5.2
GDPR Cookie Compliance to 4.12.3
WK Google Analytics to 1.8.0
Native PHP Sessions to 1.2.0
Permalink Manager Lite to 2.4.1
Regenerate Thumbnails to 3.1.5
Yoast SEO to 20.8

- [ ] http://transitbuses.wri.org/ - AWS
- [x] https://ev-simulator.wri.org/ - AWS

**Comment by gustavorf** [comment]
Pushed to dev, test and LIVE

**Comment by wthomaswri** [comment]
forestlegality, cityfix and turkiye all look good @katieescoto. Were those the only ones for now?

**Comment by monicapatel21** [comment]
Yep @wthomaswri -- thanks for the review!

https://research.wri.org/gfr/global-forest-review and https://research.wri.org/wrr-food are both paused because the other agency (New Target) has code waiting to be merged. It includes the D9 update iirc.

@katieescoto can you and Gustavo deploy updates to forestlegality, cityfix and turkiye today or tomorrow?
