### ISSUE TITLE
Layout buttons can't be pushed

### ISSUE THREAD

**Issue by mariacha** [wri/wri_sites#193]
When I try to save layout on https://www.wri.org/node/103384/layout, the logo seems to be in front of the "Save layout" button so I'm not able to save it. The Save buttons are under the menu.

There is workaround on Flagship https://www.wri.org/admin/config/development/asset-injector/css that can be deleted once this is deployed.

**Comment by mariacha** [comment]
This can be QAed on:
- [ ] Brasil: https://develop-wri-brasil.pantheonsite.io/node/100203/layout
- [ ] China:
- [ ] Indonesia:

**Comment by shannon-paton** [comment]
good on all

**Comment by mariacha** [comment]
Deployed to IOs but not yet on Flagship, so taking this back for the next deploy.

**Comment by mariacha** [comment]
Confirmed this is fixed on develop: https://develop-wriflagship.pantheonsite.io/node/103384/layout so moving to "Ready to deploy"

**Comment by mariacha** [comment]
The temporary workaround is removed on flagship, and it's still working: https://www.wri.org/node/103384/layout so I'm  closing
