### ISSUE TITLE
AWS EC2 India Prep and Hand Off

### ISSUE THREAD

**Issue by monicapatel21** [wri/wri_sites#208]
New legal requirement: India needs to launch live on AWS servers _in India_

- Assuming: we need dev/test/prod environments? Maybe we can skip?
- Or keep Pantheon for dev and test…deploy to live via AWS would be nice (change would be at final stage in deployment: test (Pantheon) to live (AWS EC2) 
- Solr would also add wrinkles
- Would also make having a CDN for performance more difficult
- If India won't have a huge number of posts, this could be OK for a time? (We may need to go for MVP version of launch and then find out what to add)

- [ ] thinkShout has AWS account credentials -- for launch -- anything else needed?
- [ ] investigate: if we try to use Pantheon's infrastructure, we can pay for a real site (and have a backup)

## Timing
1. Prioritize speccing out what we need from EC2 server
2. Pause
3. Work with India on needs -- figure out where this fits into priority

**Comment by mariacha** [comment]
Initial investigation:
https://aws.amazon.com/getting-started/hands-on/build-drupal-website/
https://aws.amazon.com/getting-started/hands-on/deploy-drupal-with-amazon-rds/

There's the part of this task that's getting Drupal to run on the site, and there's the part of this task that's creating a deployment plan.

We'll absolutely need regular backups on AWS, and the ability to roll back deploys in case of emergency.

We'll also need to set up drush access and figure out solr.

A nice workflow would be:
Deploy/QA on Pantheon
Push to Live (or test)
Push to AWS

**Comment by mariacha** [comment]
Hmm, I think that's the opposite of what we want. Aw well, it was worth a shot.

**Comment by mariacha** [comment]
I've spent a little time today continuing to investigate, and have a good shape for the work:
https://docs.google.com/document/d/1GCKPzgUGWYmaUdJdIFBwdzDYnfEc5wHShppRlFQYY7s/edit?usp=sharing

The short version is: Get started with Drupal on AWS [using Lightsail](https://aws.amazon.com/getting-started/hands-on/build-drupal-website/) provided by the [Bitnami container](https://bitnami.com/stack/drupal/containers).

Once the WRI India site is up on that instance and functioning for a handful of testers, we can get started with the finer-tuning that will be needed for go-live (caching and memory, backups).

I'll document the deployment process in this repo's wiki.

Since it's hard to estimate how long it will take to get things fully working, I'd like to approach this work from this direction.

First: Set aside a set of hours to go down the list in that Google doc and just see how far we get. I'd like to say 8 hours to start, then pause and estimate out remaining tasks.

**Comment by monicapatel21** [comment]
Internal blocker: WRI India is consulting with legal team...is the requirement relating to privacy or PCI compliance, data retention, other?

**Comment by StudioZut** [comment]
Some answers from the India team on legal requirements for data/servers:

The server location should be one in India – you would recall we had discussed the possibility of AWS, Bengaluru during our meeting with you during our call with you sometime back.

The technical architecture/design specs can be set by you in any way that you consider appropriate; we would appreciate some prior consultation with our digital team to understand the requirements and concerns, if any, at this end.

**Comment by monicapatel21** [comment]
Ideal: Pantheon for config, live site running off RDS server, Circle CI handles automation of export of config file from Pantheon to RDS
- IF: Database and data is what needs to be in-country
- IF: server needs to be in another country, then we’ll use an EC2 server within an India region, where database lives

[also some degree of IO contracting happening off line - not more budget]

**Comment by StudioZut** [comment]
Latest update with India requirements: at this point we should just work towards the full EC2 solution. We can use Pantheon through Test, then deploy from there to an AWS EC2. It looks like the India team will have their own agency handle the AWS EC2. We'll get credentials from them. 
We'll need to provide the EC2 specs. Their current site gets ~20k users a month.

**Comment by mariacha** [comment]
I've got the initial specs written up in this document and those haven't changed: 
https://docs.google.com/document/d/1GCKPzgUGWYmaUdJdIFBwdzDYnfEc5wHShppRlFQYY7s/edit#heading=h.dj729ldl8fkm

The method of spinning up the server was just what I had initially thought of, using bitnami, but I don't have strong opinions on how the server is built so long as it has the required items outlined under "What we need at launch"

**Comment by monicapatel21** [comment]
Christian to share doc with India team for review.

What ThinkShout needs is the ability to push our code up to their server. They want a versioning system on their server (something where they symlink to a new folder every time they deploy -- so they can rollback releases if needed). Having access to the database would be ideal.

Goals: Satisfy legal requirement, perception (if you check IP on server you still shouldn't see a non-India based server)

**Comment by monicapatel21** [comment]
India IO working on RFP to hire vendor, once vendor is hired, we share resources:
- Repos, databases in state it is in for migration
- Hand-off to vendor (freshly forked separate version of WRI brand and site)
- Less work and assistance for both WRI and TS

**Comment by StudioZut** [comment]
update: India's RFP is ready, we'll be helping review proposals from them

**Comment by StudioZut** [comment]
Let's stand up the dev environment on AWS and migrate the Pantheon site over.
Does it need Solr? 
AWS EC2 I assume is the best option. This will be the dev environment, so specs can be low. The India vendor will be responsible to the production environment.

**Comment by StudioZut** [comment]
India has selected a vendor (WEQ Technologies) and is signing a contract.
We're working with the India team to set up an AWS India account. Once they do we'll share credentials with TS (IAM user I guess?)

**Comment by monicapatel21** [comment]
Christian M will pick things back up this week with India finance team

**Comment by StudioZut** [comment]
Still waiting on AWS India account. The digital comms team in the India office has a new staff and we're working with them to get things back on track and working with their new vendor.

**Comment by monicapatel21** [comment]
New agency starts Oct 1 (hopefully -- if contract is signed by then)

**Comment by StudioZut** [comment]
We're walking the new India web through the AWS India signup, and will meet with their team again in October.

**Comment by StudioZut** [comment]
We have access!
I spun up the dev instance:

key file (pem):
[wri-india.zip](https://github.com/user-attachments/files/17636758/wri-india.zip)

Asia Pacific (Mumbai)
t2.small 2GiB
20GiB storage
Ubuntu 24.04 LTS
security policy open on 80, 443, SSH on 22
wri-india.pem

**Comment by monicapatel21** [comment]
- Target goal: Stood up and ready by December 1 -- Maria to start prep on this
- By then: Get a new copy of the zip file (current one's content is about a year old) -- Christian to reach out
- Handoff: Make sure new agency has same keys/access that ThinkShout has
- What will point to dev server:  india-dev.wri.org -- Christian to share this dev server with our specs (then agency determines other performance needs and works directly with India team on this)

**Comment by monicapatel21** [comment]
- ideal for handoff: up and running + migrated and current
- fall back: current version (stale) up and running

**Comment by StudioZut** [comment]
It's on the AWS India account in the Mumbai region, I have an AMI role with admin if we need to make changes outside the server.
ssh -i "wri-india.pem" ubuntu@ec2-13-232-77-228.ap-south-1.compute.amazonaws.com 

Current security group allows open access to port 22

**Comment by mariacha** [comment]
I'm moving this ticket to https://github.com/wri/WRIN/issues/491 which is a private repo instead of this one. I'll be changing the pem key and sharing it back there.
