### ISSUE TITLE
QA - Navigation 1 / 2

### ISSUE THREAD

**Issue by jordankaiser** [wri/wri_sites#213]
Design QA for PFP - Navigation 1 of 2 focusing on the desktop nav.

[PR](https://github.com/wri/wriflagship/pull/1128)

- [x] [Tasks](https://docs.google.com/document/d/1LJjQaJZ-J6MFt_4LGphcG9sdf9GPxY7dNxxN5W2FDS0/edit#heading=h.co16wcbalhxu)

Fixes:
- [x] How to fund national climate action hover nav: Links clicked on in this nav open at the target page’s middle, not page top. Should open at the page top with transparent navigation visible and hero image. Library and About pages work as expected.

**Comment by jordankaiser** [comment]
@monicapatel21 PR opened.

Assigning to @mariacha for deployment follow up.

Thanks!

**Comment by mariacha** [comment]
Example url to test with:
https://develop-wriflagship.pantheonsite.io/paying-for-paris/increasing-public-finance

Notice the behavior on live, where the  page hops you down: https://www.wri.org/paying-for-paris/increasing-public-finance

**Comment by katieescoto** [comment]
We have reviewed this on test: 
https://test-wriflagship.pantheonsite.io/paying-for-paris

**Comment by mariacha** [comment]
Since these are only relevant to Paris & Flagship, I'm closing.
