### ISSUE TITLE
QA - Navigation 2 / 2

### ISSUE THREAD

**Issue by jordankaiser** [wri/wri_sites#214]
Design QA for PFP - Navigation 2 of 2 focusing on mobile and tablet nav.

- [x] [Tasks](https://docs.google.com/document/d/1LJjQaJZ-J6MFt_4LGphcG9sdf9GPxY7dNxxN5W2FDS0/edit#heading=h.wsfv05nx2qk7)

Covers from https://github.com/wri/wriflagship/issues/1122:
- [ ] On Tablet/mobile the "< Paying for the Paris Agreement" is not clickable. When you click the arrow, it brings you back to the WRI Megamenu, but should bring you to wri.org/paying-for-paris
- [ ] Finally, can links in the subnav have some kind of differentiation if they're not clickable? "How to Fund National Climate Action" is a header and not clickable, so maybe it can just be italicized.

**Comment by jordankaiser** [comment]
@monicapatel21 PR opened.

Assigning to @mariacha for deployment follow up.

Thanks!

**Comment by mariacha** [comment]
This is reviewable at https://develop-wriflagship.pantheonsite.io/paying-for-paris
<img width="506" alt="Screenshot 2023-09-19 at 8 23 28 PM" src="https://github.com/wri/wri_sites/assets/999525/5932d870-382e-4adc-bb91-6f163178bf7a">

**Comment by shannon-paton** [comment]
Looks good except for a scroll bar showing up and blocking the menu

![Screen Shot 2023-09-20 at 9 39 51 AM](https://github.com/wri/wri_sites/assets/79596670/8360dee1-6fde-4f96-859d-815f16be186a)

**Comment by katieescoto** [comment]
This is ready to be reviewed on test @shannon-paton 
https://test-wriflagship.pantheonsite.io/paying-for-paris

**Comment by shannon-paton** [comment]
Looks good @katieescoto

**Comment by mariacha** [comment]
Since these are only relevant to Paris & Flagship, I'm closing.
