### ISSUE TITLE
QA - Home page

### ISSUE THREAD

**Issue by jordankaiser** [wri/wri_sites#216]
Design QA for home page.

- [x] [Tasks](https://docs.google.com/document/d/1LJjQaJZ-J6MFt_4LGphcG9sdf9GPxY7dNxxN5W2FDS0/edit#heading=h.n6y37djhx97w)

**Comment by jordankaiser** [comment]
Note. Wrapped up except waiting on link styling.

https://docs.google.com/document/d/1LJjQaJZ-J6MFt_4LGphcG9sdf9GPxY7dNxxN5W2FDS0/edit?disco=AAAA4ax4arA

**Comment by jordankaiser** [comment]
Done

**Comment by mariacha** [comment]
These changes have been merged to develop. We'll use https://docs.google.com/document/d/1LJjQaJZ-J6MFt_4LGphcG9sdf9GPxY7dNxxN5W2FDS0/edit#heading=h.prbyyd11rb1a for followup review
