### ISSUE TITLE
QA - Accordion based pages

### ISSUE THREAD

**Issue by jordankaiser** [wri/wri_sites#217]
Design QA for accordion based pages.

- [ ] [Tasks](https://docs.google.com/document/d/1LJjQaJZ-J6MFt_4LGphcG9sdf9GPxY7dNxxN5W2FDS0/edit#heading=h.i5ad28b0ttyv)

**Comment by jordankaiser** [comment]
@mariacha  Hey, I wanted to talk about the change mentioned [here](https://docs.google.com/document/d/1LJjQaJZ-J6MFt_4LGphcG9sdf9GPxY7dNxxN5W2FDS0/edit#heading=h.vfhqfd92tf3h). We'd like to adjust the accordion content to a maximum width of 880px.

I think the cleanest way to do this would be to insert a wrapper `div` around all of the accordion content like in the attached. I see there are some template suggestions, however I'm a little hesitant to add a new one not being familiar with what all else it might effect. Is this something that can be done?

<img width="1616" alt="SCR-20230919-jzpg" src="https://github.com/wri/wri_sites/assets/15913688/c4132726-e616-454d-b67b-448c365a8cb2">

**Comment by jordankaiser** [comment]
Popping off this for the week. Current progress in reflected in the google doc!

**Comment by mariacha** [comment]
We can add a div with a class around it within the admin area! The "Expert" DS field display allows that, so the change can be done  at `/admin/structure/paragraphs_type/accordion_item/display` by modifying the "Body" field's settings:

<img width="1041" alt="Screenshot 2023-09-20 at 12 12 55 PM" src="https://github.com/wri/wri_sites/assets/999525/770c8dc0-e4ad-4046-844d-f7aff5b983af">

you can add additional classes there.

**Comment by jordankaiser** [comment]
@mariacha Thanks for that!

Quick note on progress. All the accordion work is done with the [exception of resolving this](https://docs.google.com/document/d/1LJjQaJZ-J6MFt_4LGphcG9sdf9GPxY7dNxxN5W2FDS0/edit?disco=AAAA5KBZXbw) comment. After that we can get a PR in.

cc @monicapatel21

**Comment by monicapatel21** [comment]
Thanks @jordankaiser - opted for not worrying about vertical scroll.

**Comment by mariacha** [comment]
PR merged to develop. We'll use https://docs.google.com/document/d/1LJjQaJZ-J6MFt_4LGphcG9sdf9GPxY7dNxxN5W2FDS0/edit#heading=h.prbyyd11rb1a for re-review
