### ISSUE TITLE
Dialog theming for layout builder

### ISSUE THREAD

**Issue by mariacha** [wri/wri_sites#231]
Using layout builder now has some weird css changes
![Screen Shot 2023-10-19 at 2 30 20 PM](https://github.com/wri/wri_sites/assets/999525/215c4c83-16b0-4eb6-aca4-fb6b0d21ad43)

that's because we styled the ui-dialog to accommodate https://github.com/wri/WRIN/issues/301

and didn't realize this would affect layout builder as well.

**Comment by mariacha** [comment]
This is fixed on develop:
https://develop-wriflagship.pantheonsite.io/node/100000/layout

**Comment by shannon-paton** [comment]
Looks good @mariacha

**Comment by wthomaswri** [comment]
looks good @mariacha

**Comment by mariacha** [comment]
This is ready for review on Brasil's develop site:
https://develop-wri-brasil.pantheonsite.io/node/100251/layout

**Comment by mariacha** [comment]
Actually, I feel safe confirming it with my eyes, so just saying it's ready for deploy :)

**Comment by mariacha** [comment]
This is ready for review on the remaining IOs:
China: https://develop-wri-china.pantheonsite.io/en/research/release-957
Indonesia: https://develop-wri-indonesia.pantheonsite.io/id/publikasi/957-melepaskan
Espanol: https://develop-wri-espanol.pantheonsite.io/publicaciones/release-957-958

**Comment by wthomaswri** [comment]
Looks good @mariacha
