### ISSUE TITLE
Update Share link to use "X" with optional tweet tag add-on

### ISSUE THREAD

**Issue by mariacha** [wri/wri_sites#234]
Coming out of https://github.com/wri/wri-espanol/issues/2, share block links that appear on events pages, among others, are not translatable. This includes the text of the links (Twitter, LinkedIn), the aria text on the buttons, and the suffix on tweets (`via @WorldResource`).

This issue would fix that and anything else?

Dev note: PR opened for this here: https://github.com/wri/wri_sites/pull/233 but doesn't allow changing the name of the links, so Twitter is still that.

Update: Have block be translatable part of config so it could be changed per site and per translation if needed.

## To test
- [x] Visit a Publication and click on the Share link. See "X" Instead of "Twitter"
- [x] Click the X link to tweet. The tweet should contain `via @WorldResources`

**Comment by mariacha** [comment]
@wthomaswri I made this followup ticket for Espanol -- was there more to the hope for translating the share links?

**Comment by mariacha** [comment]
Ah, sure that makes sense.

**Comment by wthomaswri** [comment]
looks good @mariacha

**Comment by mariacha** [comment]
This is ready for review on develop for Brasil:
https://develop-wri-brasil.pantheonsite.io/publicacoes/956-release-items

**Comment by mariacha** [comment]
This is ready for review on the remaining IOs:
China: https://develop-wri-china.pantheonsite.io/en/research/release-957
Indonesia: https://develop-wri-indonesia.pantheonsite.io/id/publikasi/957-melepaskan
Espanol: https://develop-wri-espanol.pantheonsite.io/publicaciones/release-957-958

**Comment by wthomaswri** [comment]
Looks good @mariacha
