### ISSUE TITLE
Add Osano script to Head

### ISSUE THREAD

**Issue by StudioZut** [wri/wri_sites#235]
Add the Osano script to the <head> section. 

Use a Snippet to set the script ID. Set machine name as "osano_id" (example ID for flagship = 2f1a8361-e0bc-41c3-b332-023fe627c0bb)

Add immediately AFTER Google Consent Mode script "ads_data_redaction" (~ line 49)

<script src="https://cmp.osano.com/AzyfddTRtqi1560Dk/{{ contentSnippets.osano_id }}/osano.js"></script>

Note: we have been calling the script via GTM, but this is causing some issues and is not the preferred method (per Osano's docs).

**Comment by StudioZut** [comment]
PR https://github.com/wri/wri_sites/pull/236

**Comment by StudioZut** [comment]
Added option to remove script so it doesn't load in Head, since some sites might continue to load via GTM. 
This also makes it easier to troubleshoot or change vendors.

**Comment by mariacha** [comment]
This is up on develop for when we do our next deploy (so it shouldn't get lost)
https://develop-wriflagship.pantheonsite.io/

**Comment by wthomaswri** [comment]
looks good @mariacha

**Comment by mariacha** [comment]
This is ready to test on Brasil's develop site:
https://develop-wri-brasil.pantheonsite.io

When you view source for the page, you should see https://cmp.osano.com/AzyfddTRtqi1560Dk/68d76b4b-41d5-408a-8727-00456ae2d7c6/osano.js?variant=five just like on live

**Comment by mariacha** [comment]
This is ready for review on the remaining IOs:
China: https://develop-wri-china.pantheonsite.io/en/research/release-957
Indonesia: https://develop-wri-indonesia.pantheonsite.io/id/publikasi/957-melepaskan
Espanol: https://develop-wri-espanol.pantheonsite.io/publicaciones/release-957-958

**Comment by wthomaswri** [comment]
@mariacha @katieescoto i'm not seeing the script on these sites. can you verify?

**Comment by mariacha** [comment]
Yep, as long as they match what's on their live sites (which also have no scripts) we're good!
