### ISSUE TITLE
Platform: Better Passwords

### ISSUE THREAD

**Issue by StudioZut** [wri/wri_sites#272]
Assess a password tool like https://www.drupal.org/project/better_passwords.  Requires the zxcvbn-php library available at https://github.com/bjeavons/zxcvbn-php but otherwise seems straightforward.

**Comment by mariacha** [comment]
This is up and available for review at https://pr-1189-wriflagship.pantheonsite.io/admin/people/create

If you try to enter a password that's less than 12 characters, you will get an error. Weak passwords like "testtesttest" also throw errors. You also have the option of auto-generating a password for a new user. This makes a random string of characters for you. In this workflow, admins never know the generated password. New users must use the "Forgot password" link, check their emails, and generate a new password for themselves to log in for the first time. Using the auto-generated password is optional though.

<img width="864" alt="Screenshot 2024-06-12 at 10 16 26 AM" src="https://github.com/wri/wri_sites/assets/999525/96e7e43b-adb5-4bf6-9ae2-1e936499ad51">

**Comment by monicapatel21** [comment]
Note: Password reset needs SendGrid enabled on platform sites

**Comment by mariacha** [comment]
Change is up on develop:
https://develop-wriflagship.pantheonsite.io/admin/config/people/passwords

The auto-generate option is now available on Flagship since it has sendgrid set up:
https://develop-wriflagship.pantheonsite.io/admin/people/create

**Comment by monicapatel21** [comment]
Update from Shannon -- no email to @wri or @gmail accounts
Christian just enabled SendGrid on all live environments today.

Maria to take a look at develop

**Comment by mariacha** [comment]
Hmm, I did get an email sent from sendgrid:

<img width="770" alt="Screenshot 2024-06-25 at 11 51 51 AM" src="https://github.com/wri/wri_sites/assets/999525/ab60d40b-85ff-49ad-8e87-999323707cac">

@shannon-paton There's a checkbox below that is easy to miss but is required to get the email to send "Notify user of new account" -- any chance you missed checking that?

<img width="317" alt="Screenshot 2024-06-25 at 11 51 21 AM" src="https://github.com/wri/wri_sites/assets/999525/0130db21-0b1d-4d0e-83ca-65286efa9f55">

**Comment by shannon-paton** [comment]
Yep, that was it! Worked for me @mariacha

**Comment by mariacha** [comment]
I've tested this out on the IOs and will deploy tomorrow.

**Comment by mariacha** [comment]
Documented under https://docs.google.com/document/d/1p7tYALKkEFyWgWQ-MRLMKzMPP_Dlf5WV0Fe2eQM2Fqs/edit#heading=h.rhwa8jqclo1x

**Comment by mariacha** [comment]
Deployed today, so closing!
