### ISSUE TITLE
Strong tags on Programs are extra large

### ISSUE THREAD

**Issue by mariacha** [wri/wri_sites#276]
**Describe the bug**
Reported in https://github.com/wri/WRIN/issues/423 -- if you use the "B" tag on the body of a Program/center, it looks more like an h3.

Example: https://live-wri-africa.pantheonsite.io/cities

<img width="912" alt="Screenshot 2024-06-18 at 12 39 41 PM" src="https://github.com/wri/wri_sites/assets/999525/298c72bd-b643-4c33-a2e9-f79226dce8c9">

**Comment by shannon-paton** [comment]
Looks good, thanks @mariacha !

**Comment by shannon-paton** [comment]
looks good on test

**Comment by mariacha** [comment]
This is ready for review on the Develop multidevs. I've bolded part of the bodies of each of the following Programs:
https://develop-wri-brasil.pantheonsite.io/clima
https://develop-wri-china.pantheonsite.io/en/food-natural-resources
https://develop-wri-indonesia.pantheonsite.io/id/cities
https://develop-wri-espanol.pantheonsite.io/clima-y-energia

**Comment by mariacha** [comment]
Deployed today, so closing!
