### ISSUE TITLE
CityFix - Post Update issues

### ISSUE THREAD

**Issue by katieescoto** [wri/wri_sites#291]
Users report that they get a blank screen whenever they try to create a new post or edit an existing post on:

- [ ] https://thecityfix.com/
- [ ] https://thecityfixturkiye.com/

They reported this as the error:
![Image](https://github.com/user-attachments/assets/03374c68-5012-4dfe-a4fb-ebb575bc0a9a)

But that's an alert that a new update is available -- it doesn't seem to stay on the page for very long.

P-high because the team is blocked from creating/updating content

**Comment by katieescoto** [comment]
@StudioZut It looks like one of the update merges was not clean and there are missing files as a result. I've gotten a pre-update branch set up with post edits working and am working on a cleaner merge so the team can get back to editing asap.

**Comment by StudioZut** [comment]
@katieescoto thanks that's great. The content owners are hoping to get something posted this week -- should I restore the previous version on Live from backup, or do you think you'll have this fixed today/tomorrow morning?

**Comment by katieescoto** [comment]
@StudioZut I think we'll get it fixed today but I'll get you a definitive update by EOD.

**Comment by StudioZut** [comment]
Great, thank you!

**Comment by katieescoto** [comment]
@StudioZut got it. I'm almost finished with the rebase and will figure out how to deploy it without affecting anything.

**Comment by katieescoto** [comment]
@StudioZut I did a piecemeal rebase that has not solved the problem yet. I'm going to work with Maria in the morning to try an alternate approach.

**Comment by katieescoto** [comment]
@StudioZut everything should look good now on test: https://test-thecityfix-sandbox.pantheonsite.io/

I'm going to leave it up at least for today in case the team wants to test. I can aim to deploy on Monday or, if you'd prefer, after we speak on Tuesday.

**Comment by StudioZut** [comment]
Thanks @katieescoto, Cities team confirmed Test looks good. 
@monicapatel21 hopefully we can deploy cityfix and cityfixturkiye this week

**Comment by katieescoto** [comment]
Deployed CityFix Turkiye on 9/3/

**Comment by katieescoto** [comment]
Yes! And I figured out how to implement it with WP Optimize, which is the original plugin that the site had. I don't want to remove any functionality that plugin provides by using WP Super Cache instead. Depending on how it looks to users, I can deploy the same fix to both CityFix and CityFix Turkiye
