### ISSUE TITLE
Custom View for GHG Protocol

### ISSUE THREAD

**Issue by katieescoto** [wri/wri_sites#304]
Hi 
[@maria.fisher](https://thinkshout.slack.com/team/U1E21S287)
 
[@Katie Escoto (she/her)](https://thinkshout.slack.com/team/U01FT6RLDST)
 working on a custom view for ghg protocol. Wondering if you have any tips for conditional filters where if you select a parent taxonomy term it shows all the child terms. Might be a contextual filter and I'm absolutely horrible with those lol: https://events-ghgprotocol-d9.pantheonsite.io/past-events

**Comment by katieescoto** [comment]
Wil added that it pertains to the Workstream tag family

**Comment by monicapatel21** [comment]
confirmed with Wil that this is finished
