### ISSUE TITLE
wri.org -- Increase space date/time on event page

### ISSUE THREAD

**Issue by StudioZut** [wri/wri_sites#53]
On Event pages, the spacing between the end of the date and the start of the time should be increased. This screenshot from an older multidev shows how it used to appear: 
![image.png](https://images.zenhubusercontent.com/5fd8ece8f3d67d864ebe4e2b/5a782239-2b34-460b-a890-16fb5b158e85)

**Comment by komejo** [comment]
The `<time>` wrapper tag got added at some point (likely from a module upgrade) and that broke the slightly over-specific CSS.

**Comment by mariacha** [comment]
Ready for review on Flagship:
https://develop-wriflagship.pantheonsite.io/events/2022/1/terrafund-afr100-financing-innovators-restore-africas-landscapes

and China:
https://develop-wri-china.pantheonsite.io/en/events/2021/10/ecological-civilization-and-biodiversity-conservation-mainstreaming

**Comment by shannon-paton** [comment]
Looks good @mariacha

**Comment by mariacha** [comment]
Deployed to flagship: https://www.wri.org/events/2022/3/assisted-natural-regeneration-how-people-help-forests-regrow

holding here for a deployment to china.
