### ISSUE TITLE
Header logo adjustment

### ISSUE THREAD

**Issue by wthomaswri** [wri/wri_sites#64]
Would be great to look into ways to better align site logos with the top nav. It seems the formula that worked for flaghship doesn't carry across well with the IOs since their logos have more width less height: https://migrated-wri-brasil.pantheonsite.io/pt

I tried to modify the svgs but nothing seemed to work on my end unless you have a recommendation of dimensions, etc. Adding empty top/bottom space the svg didn't work as well.

## Dev
- [x] Center-align vertically all the menus on all environments.

## To test
- [ ] Review the behavior of the menus on develop compared to live for Flagship. The VR tests here are actually a pretty good way to do that for most pages: https://output.circle-artifacts.com/output/job/205a6399-942c-4634-b3fa-41f6b5ccc706/artifacts/0/artifacts/backstop_data/html_report/index.html.
- [ ] Review the behavior of the menus on develop compared to live for China. The VR tests are also a good way to check that: https://output.circle-artifacts.com/output/job/c90d1660-107b-4ac8-80cb-8a7f14e7bcda/artifacts/0/artifacts/backstop_data/html_report/index.html

**Comment by aprice42** [comment]
@wthomaswri I feel like we should be able to solve this with CSS. Seems like we could add some additional CSS logic to make sure that the items are all centered vertically in that space. 

That said, I am curious to know if you think there is a CSIS logo variation that doesn't follow the same horizontal format that we should also be aware of?

**Comment by wthomaswri** [comment]
@aprice42 yeah that sounds good to me. From what I observed it seems like the whole nav spacing is determined by the logo. Adding more bottom/top manual space in the svg itself, adds it to the adjacent menu, so whatever formula you have CSS wise could work so long that any type of logo would be set accurately.  

The flagship WRI logo is more tall that it's wide - and I think this was set to align the last text line in the WRI logo with the nav, so since the IOs only have one line that creates that empty space.

**Comment by aprice42** [comment]
@wthomaswri oh sorry, I see now, I should have looked at flagship first before making that recommendation. 

I feel like we may want to offer a setting in the theme for logo/nav alignment. We could provide two options: "align bottom" (like wriflagship) and "align center" which would look something like this:

![image](https://user-images.githubusercontent.com/675820/162329212-3ef5c318-c929-4cba-a063-d9ec57c5d64d.png)

That way flagship and any IOs with taller logos can use bottom alignment, and all other IOs can be center aligned? How does this sound?
![image](https://user-images.githubusercontent.com/675820/162329411-79e838df-c296-4cdc-ba62-51ea7a28ff54.png)

**Comment by wthomaswri** [comment]
@aprice42 sounds good

**Comment by komejo** [comment]
The semi-bottom alignment of the menu has bugged me for a while, so might I make a suggestion that would simplify everything? Just center-align the header in all cases. It already does that when you scroll, and it looks good on every site, and at every size:

![Screen Shot 2022-04-14 at 1 03 17 PM](https://user-images.githubusercontent.com/1668324/163468988-ee8568ee-d0a4-4376-ab67-a873311cb78d.png)
![Screen Shot 2022-04-14 at 1 03 24 PM](https://user-images.githubusercontent.com/1668324/163468997-7c2efb92-95a2-4345-be1e-b6d78e7e0c6f.png)
![Screen Shot 2022-04-14 at 1 03 34 PM](https://user-images.githubusercontent.com/1668324/163469001-d17b234b-baa3-4cbc-86b4-a5e609f52c0f.png)
![Screen Shot 2022-04-14 at 1 03 46 PM](https://user-images.githubusercontent.com/1668324/163469004-2bbe0016-a02c-47a2-8956-c62e51894692.png)
![Screen Shot 2022-04-14 at 1 03 56 PM](https://user-images.githubusercontent.com/1668324/163469007-2f0da7f6-eae0-4f37-8341-919835d6edda.png)
![Screen Shot 2022-04-14 at 1 04 07 PM](https://user-images.githubusercontent.com/1668324/163469009-af84e4a4-d615-4821-8352-e74061fe10f4.png)
![Screen Shot 2022-04-14 at 1 04 31 PM](https://user-images.githubusercontent.com/1668324/163469010-e025f2e7-4979-4623-8b0a-5fabe63be3f2.png)
![Screen Shot 2022-04-14 at 1 04 38 PM](https://user-images.githubusercontent.com/1668324/163469011-65d34537-45c3-421e-ad6a-673548118f69.png)
![Screen Shot 2022-04-14 at 1 04 45 PM](https://user-images.githubusercontent.com/1668324/163469012-c7753b85-93a1-493d-8309-3062de854fd6.png)
![Screen Shot 2022-04-14 at 1 12 48 PM](https://user-images.githubusercontent.com/1668324/163469014-e0f2c275-4b9a-4046-9538-70e39216e60e.png)
![Screen Shot 2022-04-14 at 1 12 55 PM](https://user-images.githubusercontent.com/1668324/163469016-1c1de978-a277-4f91-852f-ddae0834e671.png)
![Screen Shot 2022-04-14 at 1 13 03 PM](https://user-images.githubusercontent.com/1668324/163469018-5594da6a-a890-4b58-839c-a34722cfec11.png)

**Comment by wthomaswri** [comment]
@komejo Yeah I like that. Let's go with that and keep it simple and consistent across the site.

**Comment by wthomaswri** [comment]
Looks good

**Comment by mariacha** [comment]
Header logo alignment should be looking consistent on China https://wri.org.cn/en and Flagship https://www.wri.org/ now
