### ISSUE TITLE
Make footer logo match site logo

### ISSUE THREAD

**Issue by wthomaswri** [wri/wri_sites#65]
We'll need to switch the WRI logo to the IO logos across sites. Would be good if this is editable in the UI. Would be nice if we can setup a working session out of this if it's a straight forward implementation, so we can see the process.

## Dev
- [x] update footer logo so it uses the white version of the site logo

## To test
- [x] Review the logo in the footer at https://develop-wriflagship.pantheonsite.io/. It's slightly bigger than the live site. Is that ok?
- [ ] Change the "White Logo image" at https://develop-wriflagship.pantheonsite.io/admin/appearance/settings/ts_wrin. Confirm that the image changes both on the Header and Footer logo. The footer may require a cache clear.
- [ ] Visit https://develop-wri-china.pantheonsite.io/en and make sure the white logo in the footer matches the Header white logo.

**Comment by aprice42** [comment]
@wthomaswri would it make sense to use the same logo in the footer as the main site logo? We could simply use that logo in the footer as well. Otherwise, we could definitely create a logo block that would allow admins to add a new logo file. Do you have a preference?

**Comment by wthomaswri** [comment]
@aprice42 yeah if there's an easy way to route the white version of the logo to the footer as well, this will do it. I doubt we'd ever use a separate logo in the footer.

**Comment by aprice42** [comment]
@wthomaswri great I will add dev tasks above to make this happen. Happy to make this work part of a working session too if you like?

**Comment by wthomaswri** [comment]
@mariacha this looks fine on my end. I didn't replace the footer logos since it works correctly already. Looked at China as well for confirmation.

**Comment by mariacha** [comment]
We deployed this one today to live:
https://wri.org.cn/
