### ISSUE TITLE
Remove header text capitalization

### ISSUE THREAD

**Issue by wthomaswri** [wri/wri_sites#69]
Change this across all sites

header nav.menu--main.has-active-trail .menu-wrapper>ul.menu li a{
  text-transform: none;
}

It's currently: text-transform: capitalize;

- [x] Visit https://develop-wriflagship.pantheonsite.io/initiatives and see that "reach an Expert" isn't being capitalized.
- [ ] I don't believe this affects china at all, but do confirm!

**Comment by shannon-paton** [comment]
This shouldn't affect the China site. @wthomaswri  can you confirm?

**Comment by wthomaswri** [comment]
Think this should be good to go. I'm assuming the cases are left to us to decide etc with this fix so it shouldn't affect any sites. Not sure if you have any testing guidance for China since this hasn't been deployed but i'm confident it should be fine :)

**Comment by mariacha** [comment]
Yep, agreed!

**Comment by mariacha** [comment]
This went up for Brasil today. https://live-wri-brasil.pantheonsite.io/en
