### ISSUE TITLE
Clean up custom block list in layout builder

### ISSUE THREAD

**Issue by mariacha** [wri/wri_sites#75]
**Describe the bug**
If you use Layout builder on a page, your list of available blocks under "Custom" includes a lot of empty lines and blocks that have been embedded as paragraphs.

An ideal situation would make blocks created as children of Paragraphs automatically not Reusable. There's an issue in the IEF module that may help but is Postponed, but might work: https://www.drupal.org/project/inline_entity_form/issues/3002175

An easier solution may be to alter the layout builder display somehow and remove any blocks that are children of a Paragraph.

**To Reproduce**
1. Go to a node's layout builder page.
2. Click to Add a block
3. In the list of blocks see a bunch of custom blocks, including items with no name.

**Expected behavior**
You only see blocks that have been created to be truly reusable.

**Screenshots**
<img width="1207" alt="Screen Shot 2022-04-29 at 9 00 51 AM" src="https://user-images.githubusercontent.com/999525/165981455-1f203580-f230-46e7-b0a7-9012c8b7158b.png">

**Comment by mariacha** [comment]
I snuck this in to this deploy because having those empty titles was throwing a warning. To test, edit the layout on a page like https://develop-wriflagship.pantheonsite.io/node/102979/layout -- you shouldn't have a big list of empty lines under "Custom" anymore.

**Comment by wthomaswri** [comment]
This looks good @mariacha

**Comment by mariacha** [comment]
I've confirmed this on Flagship's live site -- moving to IOs for the next deploy
