### ISSUE TITLE
Hamburger nav logo

### ISSUE THREAD

**Issue by wthomaswri** [wri/wri_sites#83]
Map the logo white option to be reflected on the hamburger nav across sites.

## Dev 
- Update template to pull in white logo from theme config into hamburger menu
![2022-06-21 at 10 45 39](https://user-images.githubusercontent.com/675820/174865261-dfef7c34-22c2-4096-adcc-d9df59189120.png)

## Testing urls
This was already deployed to Brasil, but it's worth reviewing that it's working on the other IOs too:
- China: https://develop-wri-china.pantheonsite.io/
- Flagship: https://develop-wriflagship.pantheonsite.io/

**Comment by shannon-paton** [comment]
@aprice42  just noting that we will need this for the Brasil migration

**Comment by wthomaswri** [comment]
Looks good, working as expected. Tried the 40th anniversary logo on develop and mapped correctly.
