### ISSUE TITLE
Don't hard-code `/resources` for taxonomy canonical urls.

### ISSUE THREAD

**Issue by mariacha** [wri/wri_sites#89]
**Describe the bug**
Right now we h[ard-code the canonical urls for taxonomy terms to point to the `/resources` view.](https://github.com/wri/wri_sites/blob/main/modules/wri_taxonomy/wri_taxonomy.module#L102) On brasil, the path for this view is `recursos`, so none of the canonical links for tags work. On brasil, we've just not shown tag links to end users, but in future sites, we might need to do that.

**To Reproduce**
1. Visit the "Tags" taxonomy listing as an admin.
2. Click on any of the tag urls
3. See that they try to go to `/resources/tag/whatever-123` which does not resolve into a proper url.

**Expected behavior**
The url will be based on the path of the view, not on a hard-coded value. It's probably fine to pull it from the view's settings though.

## To test
- [x] Visit the /resources page and try facets -- make sure they still work.
- China: https://develop-wri-china.pantheonsite.io/resources
- Flagship: https://develop-wriflagship.pantheonsite.io/resources

**Comment by mariacha** [comment]
This has been deployed to brasil, but leaving in Review/QA for the other IOs

**Comment by shannon-paton** [comment]
Looks good @mariacha
