### ISSUE TITLE
Search pages forgets facets on sort change

### ISSUE THREAD

**Issue by mariacha** [wri/wri_sites#96]
**Describe the bug**

**To Reproduce**
1. Go to https://www.wri.org/search?keys=world
2. Filter by a content type: https://www.wri.org/search?keys=world&f%5B0%5D=content_type%3Aarticle
3. Sort by Date. Note that the filter gets lost: https://www.wri.org/search?keys=world&sort_by=created

**Expected behavior**
You're still filtering by the selected facet

**Additional context**
There's a setting for this on the view under Advanced Settings -- it's something like "use facets with exposed filters". Check that and export it to the wri_sites config.

Note that this also happens on the Experts page when you change your query: https://develop-wriflagship.pantheonsite.io/about/experts-staff?search_api_fulltext=john (and on the search page when you change your query). Get some advice on whether that is how it should be or not.

**Comment by mariacha** [comment]
Testable on Brasil at https://test-wri-brasil.pantheonsite.io/search?keys=politica&f%5B0%5D=content_type%3Aarticle

**Comment by shannon-paton** [comment]
Looks good @mariacha

**Comment by mariacha** [comment]
Deployed to live: https://www.wribrasil.org.br/search?keys=entendo&sort_by=search_api_relevance&f%5B0%5D=content_type%3Aarticle
